// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsa_zrlE1oQHvCUp2qW8Io54QGQDcaOEE',
    appId: '1:666800094897:web:9e43c1dda687455bbaac90',
    messagingSenderId: '666800094897',
    projectId: 'ahdtest-f9c78',
    authDomain: 'ahdtest-f9c78.firebaseapp.com',
    storageBucket: 'ahdtest-f9c78.firebasestorage.app',
    measurementId: 'G-2VF86PDYCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLLwfMkYJGqkVhxHt6XpF2vCV3xAq_JhE',
    appId: '1:666800094897:android:33410d3e55b7ff4bbaac90',
    messagingSenderId: '666800094897',
    projectId: 'ahdtest-f9c78',
    storageBucket: 'ahdtest-f9c78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-q50IYowLRvn8k02ioX0ZmgoMxNGlHhc',
    appId: '1:666800094897:ios:5dca7f7846514c9bbaac90',
    messagingSenderId: '666800094897',
    projectId: 'ahdtest-f9c78',
    storageBucket: 'ahdtest-f9c78.firebasestorage.app',
    iosBundleId: 'com.example.ahd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-q50IYowLRvn8k02ioX0ZmgoMxNGlHhc',
    appId: '1:666800094897:ios:5dca7f7846514c9bbaac90',
    messagingSenderId: '666800094897',
    projectId: 'ahdtest-f9c78',
    storageBucket: 'ahdtest-f9c78.firebasestorage.app',
    iosBundleId: 'com.example.ahd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsa_zrlE1oQHvCUp2qW8Io54QGQDcaOEE',
    appId: '1:666800094897:web:1782da94b74dd52cbaac90',
    messagingSenderId: '666800094897',
    projectId: 'ahdtest-f9c78',
    authDomain: 'ahdtest-f9c78.firebaseapp.com',
    storageBucket: 'ahdtest-f9c78.firebasestorage.app',
    measurementId: 'G-CBL6DH4VE6',
  );
}
